
export const GET_ARTICLES_START = "GET_ARTICLES_START";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
export const GET_EXAMS_START = "GET_EXAMS_START";
export const GET_EXAMS_SUCCESS = "GET_EXAMS_SUCCESS";
export const GET_EXAMS_ERROR = "GET_EXAMS_ERROR";
export const GET_EXAM_START = "GET_EXAM_START";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_ERROR = "GET_EXAM_ERROR";
export const ADD_EXAM = "ADD_EXAM";
export const ADD_EXAM_ERROR = "ADD_EXAM_ERROR";
export const REMOVE_EXAM = "REMOVE_EXAM";
export const REMOVE_EXAM_ERROR = "REMOVE_EXAM_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CLEAR_EXAM_MESSAGE = "CLEAR_EXAM_MESSAGE";

